### PR TITLE
Update: Feature/nwis add site filters

### PR DESCRIPTION
**Pull request by NasserMo**
Added 2 filters to the get_sites method for the USGS NWIS module.  The new site filters are bounding box (bBox on USGS site) and sites serving parameter codes (parameterCd on USGS site).  The USGS NWIS test module was also updated to test these changes: test_get_sites_by_bounding_box(),  test_get_sites_by_serving_parameter_code(), and test_get_sites_by_multiple_serving_parameter_code().

### CODE REVIEW

**Comment by wilsaj** [comment]
Looks good to me.

**Comment by dharhas** [comment]
failing tests on travis, looks like the test xml files were not committed to the repo.

**Comment by dharhas** [comment]
So this works now, the only thing is there are some failure modes. Basically if you only specify the parameter_code without specifying a bounding box etc it will give you an empty list. Looking at the NWIS documentation, one major filter (and only one) *must* be specified. Major filters are:
 
  List of sites (or just a single site) 
  State or Territory 
  Hydrologic Unit Codes 
  Latitude/Longitude Box 
  Counties 

see http://waterservices.usgs.gov/rest/Site-Test-Tool.html for details

Should we add enforce this logic or just put this in the function documentation?

- d

**Comment by NasserMo** [comment]
Maybe we could raise an exception if one of those major filters is not supplied.

**Comment by wilsaj** [comment]
:+1: on raising an exception - it would be a lot more user friendly.

**Comment by dharhas** [comment]
yes that sounds like a good way forward, we should probably also raise an exception if more that one major filter is supplied.

**Comment by dharhas** [comment]
superceded by #100

**Pull request closed without merging**
