### PR TITLE
Update twdb_fts parser

### PR DESCRIPTION
**Pull request by rhroberts**
Updated the twdb_fts parser in `ulmo/usgs/eddn/parser.py` to correctly handle battery voltage and water level data. Added test set to `ulmo/tests/usgs_eddn_test.py`.

### CODE REVIEW

**Comment by solomon-negusse** [comment]
Hi @emiliom, We are still using `usgs.eddn` in production until we finalize the `noaa.goes` module and Rusty's work here is a temporary patch that we'll later apply to `noaa.goes`.

**Comment by emiliom** [comment]
Thanks @solomon-negusse and @rhroberts. I thought USGS EDDN (the service, not the ulmo reader) was no longer available at all. So it is still usable after this PR?

I'll merge later today. Tests are passing and there are no merging issues.

**Comment by emiliom** [comment]
For tracking: this PR is related to #178

**Comment by rhroberts** [comment]
thanks, @emiliom!

**Pull request merged**
