### PR TITLE
Lcra

### PR DESCRIPTION
**Pull request by solomon-negusse**

### CODE REVIEW

**Comment by dharhas** [comment]
This is failing some lcra tests on AppVeyor (i.e. windows). I'm rerunning the tests on AppVeyor since one of the failures looks like a network issue. @solomon-negusse can you verify that the tests pass locally on windows in a conda env?

**Comment by solomon-negusse** [comment]
okay will do.

**Comment by solomon-negusse** [comment]
@dharhas i hit some issues setting up a windows vagrant box and installing conda and don't have much time to investigate further now but need to use this module for coastal geodatabase project. can we merge this and open an issue for the windows tests?

**Comment by dharhas** [comment]
@solomon-negusse You don't really need to use a vagrant box. Just use one of the windows machines you have at TWDB and setup a conda virtual environment and run the tests there. I'm a bit hesitant to merge something in with failing tests because we will never come back to them to fix them.

**Comment by dharhas** [comment]
We could also merge it in but make an windows test issue but not make a new ulmo release until we sort out the windows stuff.

**Comment by solomon-negusse** [comment]
got you. we can hold off on the merging if we won't make a new release. i can work from the branch until i get it the windows issue resolved.

**Pull request merged**
