### PR TITLE
Fix usace swtwc

### PR DESCRIPTION
**Pull request by solomon-negusse**
`usace.swtwc` data format has changed. this updates the scraper and tests for it.

### CODE REVIEW

**Comment by solomon-negusse** [comment]
not ready for merging

**Comment by dharhas** [comment]
@solomon-negusse you still working on this fix?

**Comment by solomon-negusse** [comment]
Hey Dharhas, this fell off my radar as I'm getting the data from USGS at this time. I plan to finish it up at some at some point though.  
Also, past few days I have been working on new groundwater dcp (satellite) data parser that will go into the `usgs.eddn` module and I'll submit a new PR for that next week.

**Comment by dharhas** [comment]
@solomon-negusse are you still working on this or should I close the PR?

**Comment by solomon-negusse** [comment]
hey @dharhas i haven't finished this. the module in master is broken now so if we want to keep it, i'll have to finish this fix. i'm getting the same data from nwis so this PR got neglected but can work on it later in the week.

**Comment by dharhas** [comment]
I made some small changes to the tests and got them to pass. Basically older data doesn't seem to be available any more. I'm didn't hit whatever error you were trying to fix in the date format. Also I've completely disabled mocking tests (except for eddn) accross all modules because they aren't very useful anymore unless we update all the stored files.

**Comment by emiliom** [comment]
@solomon-negusse thanks for the [follow ups yesterday!](https://github.com/ulmo-dev/ulmo/pull/168#issuecomment-475822684) I can see that the mock test [test/usace_swtwc_test.py::test_get_station_data](https://travis-ci.org/ulmo-dev/ulmo/jobs/510176416#L751) is the only usace_swtwc test that's still failing, as you mentioned in #168 and #169.

I'm merging this PR.

**Comment by solomon-negusse** [comment]
thanks @emiliom!

**Pull request merged**
