### PR TITLE
Fix twc kbdi format change

### PR DESCRIPTION
**Pull request by ajford**
As of 2016-10-01, TWC KBDI has changed the format of their summary data files from a fixed width text file to a CSV, with all past data remaining in the original format.

This PR adds a date aware switch between the data formats, as well as expanding the test suite to verify against the CSV data files. 

_Note:_ TWC also changed the formatting of DeWitt county. In previous data, they represented `DeWitt` as `De Witt`, and there is a specific FIPS mapping in the [`ulmo.twc.kbdi.core`](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/twc/kbdi/core.py#L105) that handles mapping counties to FIPS, which will properly catch both names. Any code that uses the FIPS designation should handle this change just fine, but if they use county name directly, it may be an issue. I decided against modifying the county name, however, to avoid any issues with modifying user data.

### CODE REVIEW

**Comment by dharhas** [comment]
also please add your name or github handle to the AUTHORS file so you can get credit :)

Thanks for the contribution.

**Comment by ajford** [comment]
Done! Thanks!

**Comment by ajford** [comment]
It looks like the testing is failing due to the NCDC GHCN Daily test, which is hanging on the [datafram to dict conversion](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/ncdc/ghcn_daily/core.py#L119). Converting to dict seems to take on average 15 minutes on my machine, which is outside the default timeout of Travis CI (10 minutes I think). 

According to the [Travis docs on timeout](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received), if output isn't received for 10 minutes, it's assumed the process has stalled. A debug mode (or flag) that prints some statement after every dataframe conversion might be enough to restore the build. Or some optimization of the `ulmo.util.dict_from_dataframe` routine might be in order.

**Comment by solomon-negusse** [comment]
I agree that we should try to optimize `ulmo.util.dict_from_dataframe`.. we should have a separate issue for that since it's not related to this pull request and we should get this done soon. `travis_wait` seems the appropriate way to get the build to finish (that maybe what you mean w/ debug mode). @dharhas: any thoughts/concerns?

**Comment by dharhas** [comment]
Two separate issues. 

1) Optimizing the dicts. From what I can tell, we should be able to just do replace that code with df.where((pd.notnull(df)), None).as_dict(). We don't really need to keep support for pandas <0.13 which is what some of the code in that function is doing. This should be done as a separate PR.

2) There is a failure in installing packages from conda-forge for windows. It looks like that is related to the ongoing move to conda-build 2.0 and should fix itself soon. In the meantime, the tests on windows haven't run.

If windows tests are running on your local machine, I'm fine with y'all merging, but with the caveat that I won't be making a new release version till we sort out both of the above.

**Comment by ajford** [comment]
New patch. It turns out `pandas.read_csv` takes offense to being fed an HTML page. TWC returns an HTML page when asked for a summary file that doesn't exist (such as today's file before it's released).

This wasn't an issue before, since the text file processing used `np.genfromtxt` and would force (badly) an  array from the html content, then convert to a dataframe. However, `pandas.read_csv` crashes with an error when fed HTML content. 

The new commit includes a check that the first line of the data file starts with `county`, which is the first word of the header line on both formats.

**Comment by dharhas** [comment]
@ajford, please rebase from master so the tests can run not that pr #137 has been merged.

**Pull request merged**
