### PR TITLE
0.8.5 release, prep version updates and changes log

### PR DESCRIPTION
**Pull request by emiliom**
Updated version label and CHANGES log, in preparation for new release.

### CODE REVIEW

**Comment by emiliom** [comment]
@dharhas this PR just updates the version label, CHANGES log, and some metadata in setup.py. But the CI's failed. Last time you merged PR's not too long ago, the CI's were working fine, right? 
Does it look like there's a new problem? On the [Travis CI log](https://travis-ci.org/ulmo-dev/ulmo/builds/510093205), I don't see any fatal errors, other than 5 failing tests which I assume are not fatal.

**Comment by dharhas** [comment]
I can look at it tonight.

**Comment by dharhas** [comment]
The test failures are in cpc drought and usace sw

**Comment by dharhas** [comment]
The test failures are in cpc drought and usace swtwc.

Solomon has an open PR for the usace service that he was working on a few
days ago.

CPC might be a change in test data or website.

I would open issues for those and then do a release anyway.

Dharhas

**Comment by solomon-negusse** [comment]
@dharhas `usace.swtwc` fixes are done and it's working for us now so this can be merged.. the remaining test failures related to it are due to outdated mocking data... i have opened an issue for that but didn't get a chance to look into `cpc`.

**Comment by emiliom** [comment]
Thanks @dharhas and @solomon-negusse ! I've merged PR #149 (usace swtwc). Now the 2 CPC tests and the usace.swtwc `usace_swtwc_test.py::test_get_station_data` are the only ones still failing.

I'll go ahead and merge this PR, then issue the new release.

**Pull request merged**
