### PR TITLE
Fix for issue 144 (CPC data wrap-around)

### PR DESCRIPTION
**Pull request by ajford**
Special cases the current data path to use the year column and not overwrite it with requested year.

This should resolve the problems seen in issue #144.

### CODE REVIEW

**Comment by dharhas** [comment]
fyi testing is broken right now. Looks like conda changed some of its urls so the test servers are not able to download and install conda. I'll try and get that fixed sometime soon, then we can run tests on this.

**Comment by solomon-negusse** [comment]
hey @dharhas , can this be merged now? We are pointing to this fork on wdft drought app and now we also need the fixes in the new branch in PR #148 so it'd be great if they can be merged to master. we won't need a release.

**Comment by dharhas** [comment]
I'm ok with a merge into master, I don't want to do a release till I fix the tests... Hopefully I can get to the test fixes next week.

**Comment by solomon-negusse** [comment]
Thanks!

**Pull request merged**
